apiVersion: v1
kind: LimitRange
metadata:
  name: backend-limitrange
  namespace: backend
spec:
  limits:
    - type: Container
      default:
        memory: "256Mi"
        cpu: "200m"
      defaultRequest:
        memory: "128Mi"
        cpu: "100m"
      max:
        memory: "512Mi"
        cpu: "500m"
      min:
        memory: "32Mi"
        cpu: "10m"
