apiVersion: v1
kind: ConfigMap
metadata:
  name: mood-config
  namespace: backend
data:
  PORT: "8082"
  REDIS_HOST: "redis-svc.data.svc.cluster.local"
  REDIS_PORT: "6379"
  MYSQL_HOST: "mysql-svc.data.svc.cluster.local"
  MYSQL_USER: "buzzboard"
  MYSQL_DATABASE: "buzzboard"
  REACTIONS_SVC_URL: "http://reactions-svc.backend.svc.cluster.local:8081"
