apiVersion: v1
kind: ConfigMap
metadata:
  name: reactions-config
  namespace: backend
data:
  PORT: "8081"
  REDIS_HOST: "redis-svc.data.svc.cluster.local"
  REDIS_PORT: "6379"
  MYSQL_HOST: "mysql-svc.data.svc.cluster.local"
  MYSQL_USER: "buzzboard"
  MYSQL_DATABASE: "buzzboard"
  MOOD_SVC_URL: "http://mood-svc.backend.svc.cluster.local:8082"
