apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limitrange
  namespace: frontend
spec:
  limits:
    - type: Container
      default:
        memory: "64Mi"
        cpu: "50m"
      defaultRequest:
        memory: "32Mi"
        cpu: "10m"
      max:
        memory: "128Mi"
        cpu: "100m"
      min:
        memory: "16Mi"
        cpu: "5m"
