apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "128Mi"
    limits.cpu: "500m"
    limits.memory: "256Mi"
    pods: "5"
