apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: data
type: Opaque
stringData:
  mysql-root-password: "buzzboard-mysql-root"
  mysql-password: "buzzboard-mysql-secret"
  mysql-user: "buzzboard"
  mysql-database: "buzzboard"
